# Notion configurations
[notion]
startPage = "568ac4c064c34ef6a6ad0b8d77230681"
token = "b19eea49342d67604329fbcb15bb5e9d5a5f167fed05bb2359f67605f2d53d80359cbd252b41716fb95e6d0452981f8eb814299a7555378c064635b11929cbfc3b5266d57d03f390fadedd7f6e1f"

# Hugo Blog Repo Configurations
[hugo]
repo = "https://github.com/lvntbkdmr/blog"
[hugo.user]
email = "lvntbkdmr@gmail.com"
name = "Levent Bekdemir"
[hugo.user.git]
uname = "lvntbkdmr"
token = "64252af21598022ac7f36f0d9bf59ee68a0db5d1"

# CMS Configurations
[cms]
cacheDir = "cache"
postsDir = "blog/content/posts"
imgDir = "blog/static/img"
