name: CRON Update Job

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
  
      - name: Check out source code
        uses: actions/checkout@v1
        
      - name: build the program
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: go build -o NotiGoCMS
     
      - name: Make script executable
        run: chmod +x ./setup_env.sh

      - name: Update from notion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: ./setup_env.sh
